Updated Swagger docs
ixofoundation/ixo-blocksync pull request #61
Opened 2021-08-23 16:57 UTC by stefaniatadama

2021-09-10 08:34 UTC, migueldingli1997 requested changes
`/bonds/getByBondDid/{bondDid}`: should this return a list of bonds or just one Bond?

2021-09-10 08:35 UTC, migueldingli1997 commented
Apart from the above comments, approved.

2021-09-16 11:12 UTC, stefaniatadama commented
> `/bonds/getByBondDid/{bondDid}`: should this return a list of bonds or just one Bond?

Fixed to just one bond.

2021-09-16 12:51 UTC, migueldingli1997 approved these changes

2021-09-16 12:51 UTC, merged